#!/usr/bin/env node
/**
 * Build the publishable package from `icons/icons.json`.
 *
 * Everything in `dist/` is generated — nothing in this package is written by
 * hand, which is what keeps the npm release and the repository from drifting.
 * Run `npm run build -w packages/icons` after any publish.
 *
 * Output:
 *   dist/icons.json        the manifest, verbatim
 *   dist/svg/<slug>.svg    one file per glyph
 *   dist/sprite.svg        <symbol> sprite, referenced as #termina-<slug>
 *   dist/index.js|.cjs     metadata and helpers, no React
 *   dist/react.js|.cjs     the React components
 *   dist/*.d.ts            types for both
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  N,
  componentName,
  glyphFile,
  rects,
  spriteSVG,
} from "../../glyph/index.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, "..");
const ROOT = join(PKG, "..", "..");
const DIST = join(PKG, "dist");

const manifest = JSON.parse(readFileSync(join(ROOT, "icons", "icons.json"), "utf8"));
const icons = [...manifest.icons].sort((a, b) => a.slug.localeCompare(b.slug));

rmSync(DIST, { recursive: true, force: true });
mkdirSync(join(DIST, "svg"), { recursive: true });

/* ── raw assets ──────────────────────────────────────────── */

writeFileSync(join(DIST, "icons.json"), JSON.stringify(manifest, null, 2) + "\n");
for (const icon of icons) {
  writeFileSync(join(DIST, "svg", `${icon.slug}.svg`), glyphFile(icon));
}
writeFileSync(join(DIST, "sprite.svg"), spriteSVG(icons));

/* ── metadata entry (no React) ───────────────────────────── */

const meta = icons.map((i) => ({
  name: i.name,
  slug: i.slug,
  category: i.category || "",
  tags: i.tags ?? [],
  version: i.version ?? 1,
  pixels: i.pixels,
  ...(i.credit ? { credit: i.credit } : {}),
}));

const indexBody = `/* Generated by packages/icons/scripts/build.mjs — do not edit. */

export const GRID = ${N};

/** Every glyph in the set, sorted by slug. */
export const icons = ${JSON.stringify(meta, null, 2)};

const bySlug = new Map(icons.map((i) => [i.slug, i]));

/** Look up one glyph's metadata by slug. */
export function getIcon(slug) {
  return bySlug.get(slug);
}

/** Every category in use, sorted, with "Unfiled" last. */
export function categories() {
  const set = new Set(icons.map((i) => i.category || "Unfiled"));
  return [...set].sort((a, b) =>
    a === "Unfiled" ? 1 : b === "Unfiled" ? -1 : a.localeCompare(b)
  );
}

/** Merge horizontal runs of set pixels into rectangles. */
export function toRects(pixels) {
  const out = [];
  for (let y = 0; y < GRID; y++) {
    let x = 0;
    while (x < GRID) {
      if (pixels.charCodeAt(y * GRID + x) === 49) {
        let w = 1;
        while (x + w < GRID && pixels.charCodeAt(y * GRID + x + w) === 49) w++;
        out.push({ x, y, w });
        x += w;
      } else x++;
    }
  }
  return out;
}

/**
 * SVG markup for a glyph, by slug. Returns undefined for an unknown slug
 * rather than an empty icon, so a typo is visible rather than invisible.
 */
export function toSVG(slug, { size, color = "currentColor" } = {}) {
  const icon = bySlug.get(slug);
  if (!icon) return undefined;
  const dims = size ? \` width="\${size}" height="\${size}"\` : "";
  const body = toRects(icon.pixels)
    .map((r) => \`<rect x="\${r.x}" y="\${r.y}" width="\${r.w}" height="1"/>\`)
    .join("");
  return \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 \${GRID} \${GRID}"\${dims} shape-rendering="crispEdges" fill="\${color}">\${body}</svg>\`;
}
`;

writeFileSync(join(DIST, "index.js"), indexBody);
writeFileSync(join(DIST, "index.cjs"), toCJS(indexBody));

writeFileSync(
  join(DIST, "index.d.ts"),
  `/* Generated by packages/icons/scripts/build.mjs — do not edit. */

export interface TerminaIcon {
  name: string;
  slug: string;
  category: string;
  tags: string[];
  version: number;
  /** 169 characters of "0"/"1", row-major from the top-left of a 13×13 grid. */
  pixels: string;
  credit?: string;
}

export interface Run { x: number; y: number; w: number }

export type IconSlug =
${icons.map((i) => `  | ${JSON.stringify(i.slug)}`).join("\n") || "  | never"};

export declare const GRID: ${N};
export declare const icons: TerminaIcon[];
export declare function getIcon(slug: IconSlug | (string & {})): TerminaIcon | undefined;
export declare function categories(): string[];
export declare function toRects(pixels: string): Run[];
export declare function toSVG(
  slug: IconSlug | (string & {}),
  options?: { size?: number; color?: string }
): string | undefined;
`
);

/* ── React entry ─────────────────────────────────────────── */

const components = icons.map((i) => ({ ...i, comp: componentName(i.slug) }));

/**
 * createElement rather than JSX, so the package needs no compile step and no
 * JSX runtime pinned into it. Each component spreads the caller's props last,
 * so anything can be overridden — including the fill.
 */
const reactBody = `/* Generated by packages/icons/scripts/build.mjs — do not edit. */
import { createElement, forwardRef } from "react";

const GRID = ${N};

function make(name, runs) {
  const Icon = forwardRef(function TerminaIcon(
    { size = 24, color = "currentColor", title, ...rest },
    ref
  ) {
    return createElement(
      "svg",
      {
        ref,
        xmlns: "http://www.w3.org/2000/svg",
        viewBox: \`0 0 \${GRID} \${GRID}\`,
        width: size,
        height: size,
        fill: color,
        shapeRendering: "crispEdges",
        // Decorative unless the caller gives it a title, which is the right
        // default: most icons sit beside a label that already says the word.
        role: title ? "img" : undefined,
        "aria-hidden": title ? undefined : true,
        ...rest,
      },
      title ? createElement("title", null, title) : null,
      runs.map((r) =>
        createElement("rect", {
          key: \`\${r[0]}-\${r[1]}-\${r[2]}\`,
          x: r[0],
          y: r[1],
          width: r[2],
          height: 1,
        })
      )
    );
  });
  Icon.displayName = name;
  return Icon;
}

${components
  .map(
    (i) =>
      `export const ${i.comp} = /*#__PURE__*/ make(${JSON.stringify(i.comp)}, ${JSON.stringify(
        rects(i.pixels).map((r) => [r.x, r.y, r.w])
      )});`
  )
  .join("\n")}
`;

writeFileSync(join(DIST, "react.js"), reactBody);
writeFileSync(join(DIST, "react.cjs"), toReactCJS(reactBody, components));

writeFileSync(
  join(DIST, "react.d.ts"),
  `/* Generated by packages/icons/scripts/build.mjs — do not edit. */
import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";

export interface TerminaIconProps extends Omit<SVGProps<SVGSVGElement>, "ref"> {
  /** Rendered width and height in px. Default 24. */
  size?: number | string;
  /** Fill colour. Default "currentColor". */
  color?: string;
  /** Give the icon an accessible name. Omit it for decorative icons. */
  title?: string;
}

export type TerminaIconComponent = ForwardRefExoticComponent<
  TerminaIconProps & RefAttributes<SVGSVGElement>
>;

${components.map((i) => `export declare const ${i.comp}: TerminaIconComponent;`).join("\n")}
`
);

/* ── package files ───────────────────────────────────────── */

cpSync(join(ROOT, "LICENSE"), join(PKG, "LICENSE"), { force: true });

console.log(
  `Built termina-icons: ${icons.length} glyph${icons.length === 1 ? "" : "s"}, ` +
    `${components.length} React component${components.length === 1 ? "" : "s"}.`
);

/* ── helpers ─────────────────────────────────────────────── */

/** Mechanical ESM → CJS for the generated metadata module. */
function toCJS(src) {
  return (
    src
      .replace(/^export const /gm, "const ")
      .replace(/^export function /gm, "function ") +
    `\nmodule.exports = { GRID, icons, getIcon, categories, toRects, toSVG };\n`
  );
}

function toReactCJS(src, comps) {
  return (
    src
      .replace(
        'import { createElement, forwardRef } from "react";',
        'const { createElement, forwardRef } = require("react");'
      )
      .replace(/^export const /gm, "const ") +
    `\nmodule.exports = { ${comps.map((c) => c.comp).join(", ")} };\n`
  );
}
